//priority: 998
/**
 * Global configuration for polyballs in the game.
 * When generating items, polyballs check to see if the mod is loaded before creating the item.
 * As such, removing entries from the table is not required.
 */

global.basicpolyball = [
    ['actuallyadditions:black_quartz', '#000000'],
    ['actuallyadditions:diamatine_crystal', '#00ffff'],
    ['actuallyadditions:emeradic_crystal', '#00ff00'],
    ['actuallyadditions:enori_crystal', '#ffffff'],
    ['actuallyadditions:palis_crystal', '#0000ff'],
    ['actuallyadditions:restonia_crystal', '#ff0000'],
    ['actuallyadditions:void_crystal', '#000000'],
    ['ae2:certus_quartz_crystal', '#d1d1d1'],
    ['ae2:charged_certus_quartz_crystal', '#d1d1d1'],
    ['ae2:fluix_crystal', '#a1a1a1'],
    ['appflux:harden_insulating_resin', '#ff0000'],
    ['appflux:redstone_crystal', '#ff0000'],
    ['create:brass_ingot', '#e4bb6d'],
    ['create:andesite_alloy', '#909c92'],
    ['cyclic:gem_obsidian', '#1a1a1a'],
    ['cyclic:gem_amber', '#ffbf00'],
    ['cyclic:peat_fuel', '#8b4513'],
    ['cyclic:biomass', '#228b22'],
    ['enderio:conductive_alloy_ingot', '#5567a8'],
    ['enderio:dark_steel_ingot', '#1f1f1f'],
    ['enderio:ender_crystal', '#00ff00'],
    ['enderio:end_steel_ingot', '#222222'],
    ['enderio:energetic_alloy_ingot', '#ffad2d'],
    ['enderio:pulsating_alloy_ingot', '#ff4e00'],
    ['enderio:pulsating_crystal', '#00ff00'],
    ['enderio:prescient_crystal', '#ff00ff'],
    ['enderio:soularium_ingot', '#ff6f3d'],
    ['enderio:vibrant_alloy_ingot', '#baff2d'],
    ['energizedpower:advanced_alloy_ingot', '#ff3e00'],
    ['energizedpower:energized_copper_ingot', '#db8534'],
    ['energizedpower:energized_gold_ingot', '#ffac33'],
    ['extendedcrafting:black_iron_ingot', '#333333'],
    ['extendedcrafting:crystaltine_ingot', '#a7eaff'],
    ['extendedcrafting:ender_ingot', '#5f2f3e'],
    ['extendedcrafting:enhanced_ender_ingot', '#3f2c3f'],
    ['extendedcrafting:enhanced_redstone_ingot', '#ea1e1e'],
    ['industrialforegoing:pink_slime', '#ff6ac1'],
    ['integrateddynamics:crystalized_chorus_chunk', '#d1d1d1'],
    ['integrateddynamics:crystalized_menril_chunk', '#00ff00'],
    ['mekanism:alloy_atomic', '#4d3b33'],
    ['mekanism:alloy_infused', '#7f5f5f'],
    ['mekanism:alloy_reinforced', '#5c4b48'],
    ['mekanism:fluorite_gem', '#00ff00'],
    ['mekanism:ingot_osmium', '#4e6171'],
    ['mekanism:ingot_refined_glowstone', '#ffdf7f'],
    ['mekanism:ingot_refined_obsidian', '#4b4f4f'],
    ['mekanism:ingot_uranium', '#a9d24f'],
    ['minecraft:amethyst_shard', '#9966cc'],
    ['minecraft:copper_ingot', '#e47b55'],
    ['minecraft:diamond', '#00ffff'],
    ['minecraft:emerald', '#00ff00'],
    ['minecraft:gold_ingot', '#faf25e'],
    ['minecraft:iron_ingot', '#d5d5d5'],
    ['minecraft:lapis_lazuli', '#0000ff'],
    ['minecraft:netherite_ingot', '#6a5a4d'],
    ['minecraft:prismarine_crystals', '#00ffff'],
    ['minecraft:quartz', '#ffffff'],
    ['powah:crystal_blazing', '#ff4500'],
    ['powah:crystal_niotic', '#00ffff'],
    ['powah:crystal_nitro', '#ff0000'],
    ['powah:crystal_spirited', '#00ff00'],
    ['powah:steel_energized', '#6e6e6e'],
    ['thermal:apatite', '#00ffff'],
    ['thermal:cinnabar', '#ff0000'],
    ['thermal:constantan_ingot', '#8c4d2b'],
    ['thermal:enderium_ingot', '#466789'],
    ['thermal:lumium_ingot', '#ffd166'],
    ['thermal:niter', '#ffffff'],
    ['thermal:ruby', '#ff0000'],
    ['thermal:sapphire', '#0000ff'],
    ['thermal:signalum_ingot', '#f3b200'],
    ['thermal:sulfur', '#ffff00'],
    ['thermal:xp_crystal', '#00ff00'],
    ['thermalendergy:melodium_ingot', '#ff6b6b'],
    ['thermalendergy:prismalium_ingot', '#5959b6'],
    ['thermalendergy:stellarium_ingot', '#7e7e7e'],
    ['tfmg:cast_iron_ingot', '#5e5e5e'],
    ['tfmg:lithium_ingot', '#d874a7'],
    ['tfmg:magnetic_ingot', '#787878'],
    ['tconstruct:earth_slime_crystal', '#00ff00'],
    ['tconstruct:ender_slime_crystal', '#00ff00'],
    ['tconstruct:sky_slime_crystal', '#00ffff'],
    ['tconstruct:amethyst_bronze_ingot', '#a74262'],
    ['tconstruct:cobalt_ingot', '#3f4f5f'],
    ['tconstruct:hepatizon_ingot', '#4c2265'],
    ['tconstruct:manyullyn_ingot', '#ae33ff'],
    ['tconstruct:pig_iron_ingot', '#996633'],
    ['tconstruct:queens_slime_ingot', '#7f7f9e'],
    ['tconstruct:slimesteel_ingot', '#66cc66']
];

global.tagpolyball = [
    ['#forge:ingots/aluminum', '#c0c0c0'],
    ['#forge:ingots/brass', '#e4bb6d'],
    ['#forge:ingots/bronze', '#cd5b28'],
    ['#forge:ingots/invar', '#2e2e2e'],
    ['#forge:ingots/lead', '#505f66'],
    ['#forge:ingots/nickel', '#a1a1a1'],
    ['#forge:ingots/silver', '#c0c0c0'],
    ['#forge:ingots/steel', '#444444'],
    ['#forge:ingots/tin', '#c0c0c0'],
    ['#forge:ingots/zinc', '#8f8f8f'],
    ['#forge:ingots/electrum', '#f8c600']
];


global.modpolyball = [
    ['actuallyadditions', 'tech', '#7f5f5f'],
    ['ad_astra', 'space', '#946c4c'],
    ['ae2', 'storage', '#e121d1'],
    ['create', 'tech', '#909c92'],
    ['createaddition', 'energy', '#f8c600'],
    ['cyclic', 'tech', '#909c92'],
    ['enderio', 'tech', '#4c2265'],
    ['energizedpower', 'tech', '#ff7b7b'],
    ['extendedcrafting', 'endgame', '#333333'],
    ['industrialforegoing', 'tech', '#ff3d00'],
    ['integrateddynamics', 'storage', '#ff3e00'],
    ['mekanism', 'tech', '#7f5f5f'],
    ['minecraft', 'material', '#d5d5d5'],
    ['powah', 'energy', '#6e6e6e'],
    ['tconstruct', 'material', '#3f4f5f'],
    ['tfmg', 'tech', '#5e5e5e'],
    ['thermal', 'tech', '#db8534'],
    ['thermalendergy', 'endgame', '#f13c3c']
];

global.superpolyball = [
    ['material', '#d5d5d5'],
    ['tech', '#7f5f5f'],
    ['storage', '#d1d1d1'],
    ['endgame', '#333333'],
    ['energy', '#6e6e6e']
];