//priority: 998
// Polyballs
// The scripts that utlitze these check to see if the applicable mods are loaded before doing anything, so removing entries is not required.

global.basicpolyball = [
    ['minecraft:iron', '#d5d5d5'],
    ['minecraft:copper', '#e47b55'],
    ['minecraft:gold', '#faf25e'],
    ['minecraft:netherite', '#6a5a4d'],
    ['mekanism:alloy_infused', '#7f5f5f'],
    ['mekanism:alloy_reinforced', '#5c4b48'],
    ['mekanism:alloy_atomic', '#4d3b33'],
    ['mekanism:refined_obsidian', '#4b4f4f'],
    ['mekanism:refined_glowstone', '#ffdf7f'],
    ['mekanism:osmium', '#4e6171'],
    ['mekanism:uranium', '#a9d24f'],
    ['create:andesite_alloy', '#909c92'],
    ['create:zinc', '#8f8f8f'],
    ['create:brass', '#e4bb6d'],
    ['energizedpower:tin', '#c0c0c0'],
    ['energizedpower:steel', '#444444'],
    ['energizedpower:advanced_alloy', '#ff3e00'],
    ['energizedpower:energized_copper', '#db8534'],
    ['energizedpower:energized_gold', '#ffac33'],
    ['industrialforegoing:pink_slime', '#ff6ac1'],
    ['thermal:lead', '#505f66'],
    ['thermal:silver', '#c0c0c0'],
    ['thermal:nickel', '#a1a1a1'],
    ['thermal:rose_gold', '#fcb3a7'],
    ['thermal:bronze', '#cd5b28'],
    ['thermal:invar', '#2e2e2e'],
    ['thermal:constantan', '#8c4d2b'],
    ['thermal:signalum', '#f3b200'],
    ['thermal:lumium', '#ffd166'],
    ['thermal:enderium', '#466789'],
    ['ad_astra:etrium', '#946c4c'],
    ['ad_astra:desh', '#404040'],
    ['ad_astra:ostrum', '#6c4e3b'],
    ['ad_astra:calorite', '#f05452'],
    ['extendedcrafting:black_iron', '#333333'],
    ['extendedcrafting:enhanced_redstone', '#ea1e1e'],
    ['extendedcrafting:ender', '#5f2f3e'],
    ['extendedcrafting:enhanced_ender', '#3f2c3f'],
    ['extendedcrafting:crystaltine', '#a7eaff'],
    ['thermalendergy:prismalium', '#5959b6'],
    ['thermalendergy:melodium', '#ff6b6b'],
    ['thermalendergy:stellarium', '#7e7e7e'],
    ['tfmg:cast_iron', '#5e5e5e'],
    ['tfmg:aluminum', '#c0c0c0'],
    ['tfmg:lithium', '#d874a7'],
    ['tfmg:magnetic', '#787878'],
    ['tconstruct:cobalt', '#3f4f5f'],
    ['tconstruct:slimesteel', '#66cc66'],
    ['tconstruct:amethyst_bronze', '#a74262'],
    ['tconstruct:pig_iron', '#996633'],
    ['tconstruct:queens_slime', '#7f7f9e'],
    ['tconstruct:manyullyn', '#ae33ff'],
    ['tconstruct:hepatizon', '#4c2265'],
    ['enderio:copper_alloy', '#cb6d35'],
    ['enderio:energetic_alloy', '#ffad2d'],
    ['enderio:vibrant_alloy', '#baff2d'],
    ['enderio:redstone_alloy', '#ff9a9a'],
    ['enderio:conductive_alloy', '#5567a8'],
    ['enderio:pulsating_alloy', '#ff4e00'],
    ['enderio:dark_steel', '#1f1f1f'],
    ['enderio:soularium', '#ff6f3d'],
    ['enderio:end_steel', '#222222'],
    ['megacells:sky_steel', '#6fa4c3'],
    ['powah:steel_energized', '#6e6e6e'],
    ['createaddition:electrum', '#f8c600']
];

global.modpolyball = [
    ['minecraft', 'basic', '#d5d5d5'],
    ['mekanism', 'tech', '#7f5f5f'],
    ['create', 'tech', '#909c92'],
    ['energizedpower', 'tech', '#ff7b7b'],
    ['industrialforegoing', 'tech', '#ff3e00'],
    ['thermal', 'tech', '#db8534'],
    ['ad_astra', 'space', '#946c4c'],
    ['extendedcrafting', 'endgame', '#333333'],
    ['thermalendergy', 'endgame', '#f13c3c'],
    ['tfmg', 'tech', '#5e5e5e'],
    ['tconstruct', 'tinkers', '#3f4f5f'],
    ['enderio', 'tech', '#4c2265'],
    ['powah', 'energy', '#6e6e6e'],
    ['createaddition', 'energy', '#f8c600']
];

global.superpolyball = [
    ['basic', '#d5d5d5'],
    ['tech', '#7f5f5f'],
    ['space', '#946c4c'],
    ['endgame', '#333333'],
    ['tinkers', '#3f4f5f'],
    ['energy', '#6e6e6e']
];