//priority: 998
/**
 * Global configuration for polyballs in the game.
 * When generating items, polyballs check to see if the mod is loaded before creating the item.
 * As such, removing entries from the table is not required.
 */

global.basicpolyball = [
    ['actuallyadditions:empowered_restonia_crystal', '#ff0000'],
    ['actuallyadditions:empowered_palis_crystal', '#00ff00'],
    ['actuallyadditions:empowered_emeradic_crystal', '#00ff00'],
    ['actuallyadditions:empowered_canola_seed', '#ffff00'],
    ['actuallyadditions:black_quartz', '#000000'],
    ['actuallyadditions:solidified_experience', '#00ff00'],
    ['actuallyadditions:ethetic_green_block', '#00ff00'],
    // ['tconstruct:copper_can{fluid:"actuallyadditions:empowered_oil"}', '#ff7f00'],
    ['ae2:sky_dust', '#d1d1d1'],
    ['ae2:certus_quartz_crystal', '#d1d1d1'],
    ['ae2:charged_certus_quartz_crystal', '#d1d1d1'],
    ['ae2:fluix_crystal', '#a1a1a1'],
    ['appflux:harden_insulating_resin', '#ff0000', 'ae2addon'],
    ['appflux:redstone_crystal', '#ff0000', 'ae2addon'],
    ['megacells:sky_steel_ingot', '#ff0000', 'ae2addon'],
    ['createaddition:electrum_spool', '#f8c600', 'createaddon'],
    ['create_enchantment_industry:hyper_experience_bottle', '#00ff00', 'createaddon'],
    ['tfmg:capacitor_', '#5e5e5e', 'createaddon'],
    ['tfmg:pipe_bomb', '#ff0000', 'createaddon'],
    ['create_central_kitchen:cooking_guide', '#ff4500', 'createaddon'],
    ['cyclic:gem_obsidian', '#1a1a1a'],
    ['cyclic:gem_amber', '#ffbf00'],
    ['cyclic:peat_fuel', '#8b4513'],
    ['cyclic:biomass', '#228b22'],
    ['enderio:ender_crystal', '#00ff00'],
    ['enderio:end_steel_ingot', '#222222'],
    ['enderio:pulsating_crystal', '#00ff00'],
    ['enderio:frank_n_zombie', '#00ff00', null, "32"],
    ['enderio:sentient_ender', '#00ff00', null, "32"],
    ['enderio:grains_of_infinity', '#00ff00'],
    ['energizedpower:advanced_alloy_ingot', '#ff3e00'],
    ['energizedpower:energized_copper_ingot', '#db8534'],
    ['energizedpower:energized_gold_ingot', '#ffac33'],
    ['extendedcrafting:black_iron_ingot', '#333333'],
    ['extendedcrafting:crystaltine_ingot', '#a7eaff'],
    ['extendedcrafting:ender_ingot', '#5f2f3e'],
    ['extendedcrafting:enhanced_ender_ingot', '#3f2c3f'],
    ['extendedcrafting:enhanced_redstone_ingot', '#ea1e1e'],
    ['industrialforegoing:pink_slime', '#ff6ac1'],
    ['industrialforegoing:fertilizer', '#00ff00'],
    ['industrialforegoing:plastic', '#ffffff'],
    // ['tconstruct:copper_can{fluid:"industrialforegoing:ether_gas"}', '#ff7f00', 'industrialforegoing'],
    ['integrateddynamics:crystalized_chorus_chunk', '#d1d1d1'],
    ['integrateddynamics:crystalized_menril_chunk', '#00ff00'],
    ['integratedscripting:mendesite', '#d1d1d1', 'integrateddynamics'],
    ['mekanism:alloy_atomic', '#4d3b33'],
    ['mekanism:alloy_infused', '#7f5f5f'],
    ['mekanism:alloy_reinforced', '#5c4b48'],
    ['mekanism:fluorite_gem', '#00ff00'],
    ['mekanism:ingot_osmium', '#4e6171'],
    ['mekanism:ingot_refined_obsidian', '#4b4f4f'],
    ['mekanism:hdpe_pellet', '#ffffff'],
    ['mekanism:pellet_polonium', '#00ff00', 'advancedmekanism'],
    ['mekanism:pellet_plutonium', '#00ff00', 'advancedmekanism'],
    ['mekanism:ultimate_control_circuit', '#ff0000', 'advancedmekanism'],
    ['mekanism:teleportation_core', '#ff4500', 'advancedmekanism'],
    ['minecraft:amethyst_shard', '#9966cc'],
    ['minecraft:copper_ingot', '#e47b55'],
    ['minecraft:diamond', '#00ffff'],
    ['minecraft:emerald', '#00ff00'],
    ['minecraft:gold_ingot', '#faf25e'],
    ['minecraft:iron_ingot', '#d5d5d5'],
    ['minecraft:lapis_lazuli', '#0000ff'],
    ['minecraft:netherite_scrap', '#6a5a4d', null, '128'],
    ['minecraft:prismarine_crystals', '#00ffff'],
    ['minecraft:quartz', '#ffffff'],
    ['powah:crystal_blazing', '#ff4500'],
    ['powah:crystal_niotic', '#00ffff'],
    ['powah:crystal_nitro', '#ff0000'],
    ['powah:crystal_spirited', '#00ff00'],
    ['powah:steel_energized', '#6e6e6e'],
    ['thermal:apatite', '#00ffff'],
    ['thermal:constantan_ingot', '#8c4d2b'],
    ['thermal:enderium_ingot', '#466789'],
    ['thermal:lumium_ingot', '#ffd166'],
    ['thermal:signalum_ingot', '#f3b200'],
    ['thermal:sulfur', '#ffff00'],
    ['thermal:redstone_servo', '#ff0000'],
    ['thermal:rf_coil', '#ff4500'],
    ['thermalendergy:melodium_ingot', '#ff6b6b'],
    ['thermalendergy:prismalium_ingot', '#5959b6'],
    ['thermalendergy:stellarium_ingot', '#7e7e7e'],
    ['tconstruct:sky_slime_crystal', '#00ffff'],
    ['tconstruct:amethyst_bronze_ingot', '#a74262'],
    ['tconstruct:hepatizon_ingot', '#4c2265'],
    ['tconstruct:pig_iron_ingot', '#996633'],
    ['tconstruct:queens_slime_ingot', '#7f7f9e'],
    ['create:blaze_burner', '#ff4500'],
    ['create:cogwheel', '#8b4513'],
    ['create:precision_mechanism', '#ffd700'],
    ['create:electron_tube', '#ff6347'],
    ['create:brass_casing', '#b8860b'],
    ['tconstruct:seared_brick', '#4c4c4c'],
    ['tconstruct:scorched_brick', '#4c4c4c']
];

global.tagpolyball = [
    ['#forge:ingots/aluminum', '#c0c0c0'],
    ['#forge:ingots/brass', '#e4bb6d'],
    ['#forge:ingots/bronze', '#cd5b28'],
    ['#forge:ingots/invar', '#2e2e2e'],
    ['#forge:ingots/lead', '#505f66'],
    ['#forge:ingots/nickel', '#a1a1a1'],
    ['#forge:ingots/silver', '#c0c0c0'],
    ['#forge:ingots/steel', '#444444'],
    ['#forge:ingots/tin', '#c0c0c0'],
    ['#forge:ingots/zinc', '#8f8f8f'],
    ['#forge:ingots/electrum', '#f8c600']
];

global.modpolyball = [
    ['actuallyadditions', 'tech', '#7f5f5f', 'actuallyadditions:ender_casing'],
    // ['ad_astra', 'space', '#946c4c', 'ad_astra:etrionic_core'],
    ['ae2', 'storage', '#e121d1', 'ae2:condenser'],
    ['ae2addon', 'storage', '#e121d1', 'expatternprovider:circuit_cutter', "true"],
    ['create', 'tech', '#909c92', 'create:railway_casing'],
    ['createaddon', 'tech', '#f8c600', 'create:copper_casing', "true"],
    ['cyclic', 'tech', '#909c92', 'kubejs:reinforced_stone'],
    ['enderio', 'tech', '#4c2265', 'enderio:ensouled_chassis'],
    ['energizedpower', 'tech', '#ff7b7b', 'energizedpower:reinforced_advanced_machine_frame'],
    ['extendedcrafting', 'endgame', '#333333', 'extendedcrafting:nether_star_block'],
    ['industrialforegoing', 'tech', '#ff3d00', 'industrialforegoing:machine_frame_supreme'],
    ['integrateddynamics', 'storage', '#ff3e00', 'integrateddynamics:variablestore'],
    ['mekanism', 'tech', '#7f5f5f', 'mekanism:steel_casing'],
    ['advancedmekanism', 'endgame', '#7f5f5f', 'mekanism:antiprotonic_nucleosynthesizer', "true"],
    ['minecraft', 'material', '#d5d5d5', 'extendedcrafting:nether_star_block'],
    ['powah', 'energy', '#6e6e6e', 'powah:dielectric_casing'],
    ['tconstruct', 'material', '#3f4f5f', 'tconstruct:slimesteel_reinforcement'],
    ['thermal', 'tech', '#db8534', 'thermal:machine_frame'],
    ['thermalendergy', 'endgame', '#f13c3c', 'thermalendergy:vibrating_core']
];

global.superpolyball = [
    ['material', '#d5d5d5'],
    ['tech', '#7f5f5f'],
    ['storage', '#d1d1d1'],
    ['energy', '#6e6e6e'],
    ['endgame', '#333333']
];